# 语言文件 [可选 中文简体:zh_CN;中文繁體:zh_TW;English:en_US]
language: zh_CN

# 是否开启更新提醒,建议开启
isCheckUpdate: true

# OP登录时候是否发送更新提醒
isCheckUpdateToOpMsg: true

# 皮肤站管理员上线自动获得OP
isAdminJoinGetOp: true

# 皮肤站封禁玩家上线自动踢出
isBannedJoinKick: true

# BSE-API (BlessingSkin配套插件)
# 查看BSE-API配置页面
BSE-API: "http://192.168.23.133/BSE-API/"
# 在BSE-API配置页面设置
BSE-API-TOKEN: "1"

